# Create vm if it does not exist yet - createvm.yaml
- name: Create VM if it does not exist
  block:
    - name: Download fc39 base image
      get_url:
        url: "{{ fc_base_image_url }}"
        dest: "/tmp/{{ fc_base_image_name }}"
        checksum: "sha256:{{ fc_base_image_sha }}"
      when: vm_os == "fedora"

    - name: Download centos stream 9 base image
      get_url:
        url: "{{ ce_base_image_url }}"
        dest: "/tmp/{{ ce_base_image_name }}"
        checksum: "sha256:{{ ce_base_image_sha }}"
      when: vm_os == "centos"

    - name: Create a static network config in /tmp if vm_ip is defined
      ansible.builtin.template:
        src: ifcfg-eth0.j2
        dest: /tmp/ifcfg-eth0
        owner: root
        group: wheel
        mode: '0640'
      when: static_ip | bool

    - name: Copy given base image to libvirt directory
      copy:
        src: "/tmp/{{ fc_base_image_name }}"
        dest: "{{ vm_pool_dir }}/{{ vm_name }}.qcow2"
        force: false
        remote_src: true
        mode: 0660
      register: copy_results
      when: vm_os == "fedora"

    - name: Copy given base image to libvirt directory
      copy:
        src: "/tmp/{{ ce_base_image_name }}"
        dest: "{{ vm_pool_dir }}/{{ vm_name }}.qcow2"
        force: false
        remote_src: true
        mode: 0660
      register: copy_results
      when: vm_os == "centos"

    - name: Resize the base image by 10GB and extend the filesystem as well
      shell:
        "{{ item }}"
      with_items:
        - qemu-img resize {{ vm_pool_dir }}/{{ vm_name }}.qcow2 +10G
        - cp {{ vm_pool_dir }}/{{ vm_name }}.qcow2 {{ vm_pool_dir }}/{{ vm_name }}-orig.qcow2
        - virt-resize --expand /dev/sda1 {{ vm_pool_dir }}/{{ vm_name }}-orig.qcow2 {{ vm_pool_dir }}/{{ vm_name }}.qcow2
        - rm {{ vm_pool_dir }}/{{ vm_name }}-orig.qcow2
      when: resize_vm | bool

    - name: Configure the VM image with static IP if vm_ip is defined
      command: |
        virt-customize -va {{ vm_pool_dir }}/{{ vm_name }}.qcow2 \
        --hostname {{ vm_name }} \
        --run-command 'useradd -m {{ user }}' \
        --root-password password:{{ vm_root_pass }} \
        --copy-in /etc/sudoers.d/{{ user }}_nopasswd:/etc/sudoers.d/ \
        --copy-in /tmp/ifcfg-eth0:/etc/sysconfig/network-scripts/ \
        --ssh-inject {{ user }}:file:{{ user_pub_ssh_key }} \
        --uninstall cloud-init \
        --selinux-relabel
      when: static_ip is defined

    - name: Configure the vm image with DHCP if vm_ip is undefined
      command: |
        virt-customize -va {{ vm_pool_dir }}/{{ vm_name }}.qcow2 \
        --hostname {{ vm_name }} \
        --run-command 'useradd -m {{ user }}' \
        --copy-in /etc/sudoers.d/{{ user }}_nopasswd:/etc/sudoers.d/ \
        --ssh-inject {{ user }}:file:{{ user_pub_ssh_key }} \
        --uninstall cloud-init \
        --selinux-relabel
      when: copy_results is changed and static_ip is undefined

    - name: Define the VM
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'vm-template.xml.j2') }}"
      when: "vm_name not in existing_vms.list_vms"
