# Delete /tmp if cleanup was set to "yes"

- name: Cleanup in /tmp
  block:
    - name: Delete temp image in /tmp
      file:
        path: "/tmp/{{ fc_base_image_name }}"
        state: absent
      when: vm_os == "fedora"

    - name: Delete temp image in /tmp
      file:
        path: "/tmp/{{ ce_base_image_name }}"
        state: absent
      when: vm_os == "centos"

    - name: Delete ifcfg file in /tmp
      file:
        path: "/tmp/ifcfg-eth0"
        state: absent

  when: cleanup_tmp | bool
