---
# tasks file for libvirt-vm

- name: See if all required pkgs are in place
  include_tasks: checkreqs.yaml
 
- name: Get VMs list
  include_tasks: vmlist.yaml

- name: Create VM if it does not exist
  include_tasks: createvm.yaml

- name: Ensure VM is started
  include_tasks: startvm.yaml

- name: Delete temp files created in /tmp
  include_tasks: garbagecoll.yaml
