---
# handlers file for cfssl-pki

- name: generate_ca
  ansible.builtin.shell: cfssl gencert -initca {{ cfssl_config_dir }}/{{ cfssl_ca_config_file }} | cfssljson -bare ca
  args:
    chdir: "/opt/ssl"
  
- name: generate_intermediate_ca
  ansible.builtin.shell: cfssl gencert -initca {{ cfssl_config_dir }}/{{ cfssl_interm_config_file }} | cfssljson -bare intermediate_ca
  args: 
    chdir: "/opt/ssl"
