---
# handlers file for cfssl-pki

- name: generate_ca
  ansible.builtin.shell: cfssl gencert -initca {{ cfssl_config_dir }}/{{ cfssl_ca_config_file }} | cfssljson -bare ca
  args:
    chdir: "/opt/ssl"
    creates:
      - "/opt/ssl/ca.pem"
      - "/opt/ssl/ca-key.pem"
      - "/opt/ssl/ca.csr"
- name: generate_intermediate_ca
  ansible.builtin.shell: cfssl gencert -initca {{ cfssl_config_dir }}/{{ cfssl_interm_config_file }} | cfssljson -bare intermediate_ca
  args: 
    chdir: "/opt/ssl"
    creates:
      - "/opt/ssl/intermediate_ca.pem"
      - "/opt/ssl/intermediate_ca-key.pem"
      - "/opt/ssl/intermediate_ca.csr"