- name: Install Gitlab on a Fedora 34/CentOS 8 server
  hosts: sbxhosts
  environment:
    GITLAB_ROOT_PASSWORD: "{{ gitlab_root_pwd }}"
  gather_facts: true
  become: true
  tasks:
    - name: install Gitlab role
      include_role:
        name: gitlab-vm-lab
