---
- hosts: all
  tasks:
    - name: Add nextdns repo
      yum_repository:
        name: nextdns
        description: "Repo for NextDNS on Fedora server"
        baseurl: https://repo.nextdns.io/rpm
        enabled: 1
        gpgcheck: 0
        repo_gpgcheck: 1
        gpgkey: https://repo.nextdns.io/nextdns.gpg
      become: true
    - name: Install nextDNS
      dnf:
        name: nextdns
        state: present
        update_cache: true
      become: true
