- hosts: labhosts
  tasks:
    - name: Update cache
      apt:
        update_cache: true
        upgrade: dist
        autoremove: true

    - name: Upgrade all packages on servers
      apt:
        name: "*"
        state: present
    - name: Reboot
      reboot:
  become: true
