---
# handlers file for sonarqube-host

- name: enable_postgresql
  service:
    name: postgresql
    enabled: true

- name: init_postgresql
  command: |
    /usr/bin/postgresql-setup --initdb
  register: postgres_initialized

- name: start_postgresql
  service:
    name: postgresql
    state: started
  register: postgresql_started
