---
# handlers file for sonarqube-host

- name: enable_postgresql
  service:
    name: postgresql
    enabled: true

- name: init_postgresql
  command: |
    /usr/bin/postgresql-setup --initdb
  register: postgres_initialized

- name: start_postgresql
  service:
    name: postgresql
    state: started
  register: postgresql_started

- name: restart_sonarqube
  service:
    name: "{{ sonar_user }}"
    state: restarted
  register: sonar_restarted

- name: restart_nginx
  service:
    name: nginx
    state: restarted
  register: nginx_restarted
