---
# tasks file for gitlab-vm-lab

- name: Install prerequisites
  include_tasks: prerequisites.yml

- name: Install postfix
  include_tasks: install-postfix.yml

- name: Install Gitlab-ce
  include_tasks: install-gitlab.yml
