---
# tasks file for cfssl-pki

- name: Install go
  yum: 
    name: go
    state: latest
    update_cache: true

- name: Downloading & installing cfssl binaries
  ansible.builtin.command: go get {{ cfssl_github_uri }}

- name: Check if the ssl config directory exists
  stat:
    path: "{{ cfssl_config_dir }}" 
  register: config_dir

- name: Create ssl/config folder in /opt
  file:
    path: "{{ cfssl_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  when: not config_dir.stat.exists

- name: Copy basic configs ca, intermediate and cfssl into /opt/ssl/config
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  loop:
    - { src: 'roles/cfssl-pki/templates/{{ cfssl_interm_config_file }}.j2', dest: '{{ cfssl_config_dir }}/{{ cfssl_interm_config_file }}' }
    - { src: 'roles/cfssl-pki/templates/{{ cfssl_ca_config_file }}.j2', dest: '{{ cfssl_config_dir }}/{{ cfssl_ca_config_file }}' }
    - { src: 'roles/cfssl-pki/templates/{{ cfssl_config_file }}.j2', dest: '{{ cfssl_config_dir }}/{{ cfssl_config_file }}' }
  notify:
    - generate_ca
    - generate_intermediate_ca
  
