---
# tasks file for cfssl-pki

- name: Load variables based on OS type 
  include_tasks: osvars.yml

- name: Install go on ca host
  include_tasks: go.yml
  when: ca_store == 'true'

- name: Install cfssl & prepare cfssl configs 
  include_tasks: cfssl.yml
  when: ca_store == 'true'

- name: Create install and distribute CA & Intermediate
  include_tasks: ca.yml

- name: Create & distribute host certs
  include_tasks: hostcerts.yml
  