# Delete /tmp if cleanup was set to "yes"

- name: Delete temp image in /tmp
  file:
    path: "/tmp/{{ base_image_name }}"
    state: absent
  when: cleanup_tmp | bool

- name: Delete ifcfg file in /tmp
  file:
    path: "/tmp/ifcfg-eth0"
    state: absent
  when: cleanup_tmp | bool

