- name: Install go for RHEL family
  dnf:
    name: go
    state: present
    update_cache: true
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'
  run_once: true

- name: Install go for Ubuntu
  apt:
    name: go
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu'
  run_once: true
