- name: install docker
  apt:
    name: docker
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu'
  notify: restart_docker

- name: install docker on Fedora
  dnf:
    name: docker-distribution
    state: present
    update_cache: true
  when: ansible_distribution == 'Fedora'
  notify: restart_docker

- name: install docker on CentOS
  yum:
    name: docker-ce
    state: present
    update_cache: true
  when: ansible_distribution == 'CentOS'
  notify: restart_docker
