---
# tasks file for nomad-cluster-node
- name: Load variables based on OS type 
  include_tasks: osvars.yml
- name: Install openjdk 11 runtime 
  include_tasks: openjdk-11.yml
  when: nomad_node is defined
- name: Install docker runtime
  include_tasks: docker.yml
  when: nomad_node is defined
- name: Install HashiCorp repository
  include_tasks: hashirepo.yml
- name: Install Nomad
  include_tasks: nomad.yml
- name: Install Consul
  include_tasks: consul.yml
- name: Install Vault
  include_tasks: vault.yml

