# Get all prerequisites loaded and installed

- name: Load a variable file based on the OS type
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ansible_distribution|lower}}-vars.yml'
    - main.yml