---
# Download and install sonarqube

- name: Download Sonarqube zip
  get_url:
    url: "{{ sonar_src }}"
    dest: "/opt/sonarqube-{{ sonar_version }}.zip"

- name: Unpack sonarqube
  unarchive:
    src: "/opt/sonarqube-{{ sonar_version }}.zip"
    dest: "/opt"
    copy: false
    owner: "{{ sonar_user }}"
    group: "{{ sonar_user }}"

- name: Softlink to sonar home
  file:
    src: "/opt/sonarqube-{{ sonar_version }}"
    dest: "{{ sonar_home }}"
    state: link
    owner: "{{ sonar_user }}"
    group: "{{ sonar_user }}"

- name: Customize sonarqube config
  template:
    src: roles/sonarqube-host/templates/sonar.properties.j2
    dest: "{{ sonar_path_config }}"
    mode: '0640'
    owner: "{{ sonar_user }}"
    group: "{{ sonar_user }}"

- name: Customize wrapper config
  template:
    src: roles/sonarqube-host/templates/wrapper.conf.j2
    dest: "{{ sonar_path_config }}"
    mode: '0640'
    owner: "{{ sonar_user }}"
    group: "{{ sonar_user }}"

- name: Sonar systemd service
  template:
    src: roles/sonarqube-host/templates/sonarqube.service.j2
    dest: "{{ sonar_path_service }}"
    mode: '0640'
    owner: root
    group: wheel

- name: Create sonarqube logs directory
  file:
    path: "{{ sonar_path_logs }}"
    state: directory
    mode: '0750'
    owner: "{{ sonar_user }}"
    group: wheel
