---
# install nginx

- name: Install nginx
  dnf:
    name: nginx
    state: present
    update_cache: true

- name: Configure proxy for sonarqube
  template:
    src: roles/sonarqube-host/templates/sonar-nginx.conf.j2
    dest: "{{ nginx_path_conf }}"
    mode: '0640'
  notify: restart_nginx
