---
# Install basic pgsql
- name: install postgresql
  dnf:
    name: ["{{ pgsql_pkg_server_name }}", "{{ pgsql_pkg_client_name }}"]
    state: present
    update_cache: true

- name: Enable postgresql
  service:
    name: postgresql
    enabled: true
  notify:
    - enable_postgresql
    - init_postgresql
  when: postgresql_initialized is undefined

- name: Start postgresql
  service:
    name: postgresql
    state: started
  notify: start_postgresql
  when: postgresql_started is undefined

- name: Install psycopg2 binary for pg module
  pip:
    name: psycopg2-binary
    executable: pip3


- name: Create a new sonar db with UTF-8 encoding
  become: true
  become_user: "{{ pgsql_user }}"
  postgresql_db:
    name: "{{ pgsql_sonar_db }}"
    encoding: UTF-8
    template: template0
    state: present
  register: sonar_db_created

- name: Create sonarqube db user and assign it to the sonar db
  become: true
  become_user: "{{ pgsql_user }}"
  postgresql_user:
    db: "{{ pgsql_sonar_db }}"
    name: "{{ pgsql_sonar_db }}"
    password: "{{ pgsql_sonar_pwd }}"
    priv: ALL
  when: sonar_db_created | bool
