---
# Install basic pgsql
- name: install postgresql
  dnf:
    name: ["{{ pgsql_pkg_server_name }}", "{{ pgsql_pkg_client_name }}"]
    state: present
    update_cache: true

- name: Enable postgresql
  service:
    name: postgresql
    enabled: true
  notify:
    - enable_postgresql
    - init_postgresql
  when: postgresql_initialized is undefined

- name: Start postgresql
  service:
    name: postgresql
    state: started
  notify: start_postgresql
  when: postgresql_started is undefined

- name: Create sonar user and db in postgresql
  block:

    - name: Create sonarqube db user and assign it to the sonar db
      become: true
      become_user: "{{ pgsql_user }}"
      postgresql_user:
        name: "{{ pgsql_sonar_user }}"
        password: "{{ pgsql_sonar_pwd }}"
        state: present

    - name: Create a new sonar db with UTF-8 encoding
      become: true
      become_user: "{{ pgsql_user }}"
      postgresql_db:
        name: "{{ pgsql_sonar_db }}"
        encoding: UTF-8
        template: template0
        owner: "{{ pgsql_sonar_user }}"
        state: present
