---
# tasks file for sonarqube-host
- name: Recognize ostype
  include_tasks: whichos.yml

- name: Set SELinux permissive
  include_tasks: setselinper.yml
  when: ostype == "fedora" or ostype == "centos"

- name: Install postgresql on Fedora
  include_tasks: install-pgsql.yml

- name: Install openjdk-11 on Fedora
  include_tasks: install-openjdk-11.yml

- name: Create sonar user
  include_tasks: sonar-user.yml

- name: Install sonarqube
  include_tasks: install-sonar.yml

- name: Install nginx
  include_tasks: install-nginx.yml
