---
# tasks file for sonarqube-host
- name: Recognize ostype
  include_tasks: whichos.yml

- name: Set prerequisites for sonar and pgsql
  include_tasks: prerequisites.yml

- name: Install postgresql on Fedora
  include_tasks: install-pgsql.yml

- name: Create sonar user
  include_tasks: sonar-user.yml

- name: Install sonarqube
  include_tasks: install-sonar.yml

- name: Install nginx
  include_tasks: install-nginx.yml
