---
# Install all required components
- name: Install psycopg2 binary for pg module
  pip:
    name: psycopg2-binary
    executable: pip3

- name: Install openjdk-11
  dnf:
    name: java-11-openjdk
    state: present
    update_cache: true

- name: Install python3 libselinux
  dnf:
    name: python3-libselinux
    state: present
    update_cache: true
  register: py3_selib

- name: Enable SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: py3_selib | bool

- name: set sysctl
  command: |
    sysctl -w vm.max_map_count=262144

- name: Put sysctl settings for elasticsearch
  template:
    src: roles/sonarqube-host/templates/elastic.conf.j2
    dest: "{{ elastic_path_conf }}"
    mode: '0640'
