---
# Set SELinux permissive on the lab vm
- name: Install python3 libselinux
  dnf:
    name: python3-libselinux
    state: present
    update_cache: true
  register: py3_selib

- name: Enable SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: py3_selib | bool
