---
# Local DNS setup
host_local_dns: 192.168.130.1

# TLS/SSL setup
host_tls_cert_store: /etc/pki/tls/certs
host_tls_key_store: /etc/pki/tls/private
host_tls_port: 443

# Gitlab repository
gitlab_ce_install_script_url: 'https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh'
gitlab_ce_baseurl: 'https://packages.gitlab.com/gitlab/gitlab-ce/el/8/$basearch'
gitlab_ce_path_yum_repo: /etc/yum.repos.d/gitlab-ce.repo

# Gitlab settings
gitlab_web_port: 80

# set at inventory through hostvar
gitlab_root_pass: "{{ gitlab_root_pwd }}"

gitlab_path_conf: /etc/gitlab
gitlab_path_data: /opt/gitlab/data
gitlab_path_bkp: /opt/gitlab/backups
gitlab_conf_file: gitlab.rb
gitlab_host_domain: nukelab.home
gitlab_external_url: "https://{{ ansible_hostname }}.{{ gitlab_host_domain }}"
gitlab_timezone: "UTC+1"
gitlab_bkp_keep_time: "604800"
gitlab_default_theme: '2'

# Gitlab TLS settings
gitlab_redirect_http_to_https: true
gitlab_ssl_cert: "{{ host_tls_cert_store }}/{{ ansible_hostname }}-peer.pem"
gitlab_ssl_cert_key: "{{ host_tls_key_store }}/{{ ansible_hostname }}-peer-key.pem"

# Gitlab extra services settings
gitlab_ldap_enabled: false
gitlab_smtp_enabled: false
gitlab_email_enabled: false
gitlab_letsencrypt_enabled: false
gitlab_prometheus_enabled: false
gitlab_grafana_enabled: false
gitlab_node_exporter_enabled: false

# Gitlab container registry settings
gitlab_registry_enabled: true
gitlab_registry_external_url: "{{ gitlab_external_url }}:9443"
gitlab_registry_nginx_ssl_cert: "{{ gitlab_ssl_cert }}"
gitlab_registry_nginx_ssl_cert_key: "{{ gitlab_ssl_cert_key }}"
