---
- hosts: all
  tasks:
    - name: Install snapd
      dnf:
        name: snapd
        state: latest
        update_cache: True
      become: true

    - name: Start snapd service
      ansible.builtin.systemd:
        name: snapd
        state: started
        enabled: true
      become: true
