---
# Install python-selinux bindings for cert provisioning and gitlab installation
- hosts: sbxhosts
  tasks:
    - name: Install python-selinux binding
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-libselinux
        - policycoreutils-python-utils
        - python3-policycoreutils
      become: yes
