---
- hosts: labhosts
  tasks:
    - name: sudo without password for a user
      ansible.builtin.copy:
        content: 'hobbes ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/hobbes_nopasswd
        mode: 0440
        owner: root
        group: root
        force: yes
      become: yes
