---
# tasks file for nomad-cluster-node
- name: install docker
  apt:
    name: docker
    state: present
    update_cache: yes

- name: install zip
  apt: 
    name: zip
    state: present
    update_cache: yes

- name: install openjdk-11
  apt: 
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: add apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: install nomad repo
  apt_repository: 
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release }} main
    state: present
    filename: nomad
    update_cache: yes

- name: install nomad
  apt:
    name: nomad
    state: present
    update_cache: yes

- name: install consul
  apt:
    name: consul
    state: present
    update_cache: yes

- name: install vault
  apt:
    name: vault
    state: present
    update_cache: yes
