- name: Install nomad on Ubuntu
  apt:
    name: nomad
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and nomad_node is defined

- name: Install nomad on CentOS/Fedora
  dnf:
    name: nomad
    state: latest
    update_cache: True
  when: (ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS') and (nomad_node is defined)

- name: install nomad config        
  template:
    src: roles/nomad-cluster-node/templates/nomad.hcl.j2
    dest: "{{ nomad_home }}/nomad.hcl"
  changed_when: true
  notify: restart_nomad
  when: nomad_node is defined