- name: install openjdk-11
  apt: 
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install openjdk-11 on CentOS/Fedora
  dnf:
    name: java-11-openjdk
    state: latest
    update_cache: True
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'