name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v4
    - name: Ansible Linter
      uses: ansible/ansible-lint@v6
      with:
        targets: ""
